// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAccountMenu: typeof import('./src/app/components/AppAccountMenu.vue')['default']
    AppCard: typeof import('./src/app/components/AppCard.vue')['default']
    AppDialog: typeof import('./src/app/components/AppDialog.vue')['default']
    AppDrawer: typeof import('./src/app/components/AppDrawer.vue')['default']
    AppNetworkError: typeof import('./src/app/components/AppNetworkError.vue')['default']
    AppPage: typeof import('./src/app/components/AppPage.vue')['default']
    AppPageHeader: typeof import('./src/app/components/AppPageHeader.vue')['default']
    AvatarChip: typeof import('./src/app/components/AvatarChip.vue')['default']
    DashboardHeader: typeof import('./src/app/components/headers/DashboardHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCreateDialog: typeof import('./src/app/components/dialogs/UserCreateDialog.vue')['default']
    UserHeader: typeof import('./src/app/components/headers/UserHeader.vue')['default']
    VInput: typeof import('./src/app/components/form/VInput.vue')['default']
    VSelect: typeof import('./src/app/components/form/VSelect.vue')['default']
  }
}
