# HTTP / HTTPS server settings
http:
  # If you change the server port you have to change it also on the front-end
  port: 3000 

  # If true it starts the HTTPS server
  # Note that you need to fill in the credentials fields for the SSL certificate
  secure: false

  # If secure option is set to true you must define the paths for the SSL certificate
  credentials:
    key: 'PATH_TO_KEY_DIR/key.pem'
    cert: 'PATH_TO_CERT_DIR/cert.pem'

  # Cross-Origin Resource Sharing domain origins 
  # More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
  cors: 
    - 'http://localhost:8080'

# Database server settings
# More info: https://typeorm.io
db:
  # Database type (postgres, mysql etc.)
  type: 'postgres' 

  # Database server address
  host: 'localhost' 

  # Database server port
  port: 5432

  # Database name
  database: ''

  # Database username
  username: ''

  # Database password
  password: ''

  # Disable this in the production version of the application
  synchronize: true

# Keys required for hashing passwords and tokens
# They should be filled with random, unique strings
keys:
  pwdsalt: ''
  jwt: ''
